app:
  build: .
  dockerfile: Dockerfile.dev
  volumes:
    - .:/app
  ports:
    - "3000:3000"
  links:
    - datastore
  environment:
    DATASTORE_EMULATOR_HOST: datastore:8181

datastore:
  image: vyper/gcd-grpc
  expose:
    - "8181"
