app:
  build: .
  dockerfile: Dockerfile.dev
  volumes:
    - .:/app:Z
  ports:
    - "3000:3000"
  links:
    - db:postgres
  environment:
    POSTGRES_USER: app
    POSTGRES_PASSWORD: password
    USERNAME: app
    PASSWORD: password

db:
  image: postgres:9.4.5
  ports:
    - "5432:5432"
  volumes:
    - graph_notes_data:/var/lib/postgresql/data:Z
  environment:
    POSTGRES_USER: app
    POSTGRES_PASSWORD: password
